# Generated by Django 3.0.3 on 2021-06-07 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=10, verbose_name='Phone Number')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_up', verbose_name='Profile Picture')),
                ('company_name', models.CharField(blank=True, default='N/A', max_length=60, verbose_name='Registered Name of Company')),
                ('company_logo', models.ImageField(blank=True, upload_to='logo_up', verbose_name='Company Logo')),
                ('company_docs', models.FileField(blank=True, upload_to='docs_up', verbose_name='Company Registration Documents')),
                ('service_provided', models.CharField(blank=True, choices=[('1', 'Service Type 1'), ('2', 'Service Type 2'), ('3', 'Service Type 3'), ('4', 'Service Type 4'), ('5', 'Service Type 5')], default='N/A', max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
